import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>

                {/* Navigation Menu */}
      <nav className="border-b">
        <div className="max-w-4xl mx-auto px-8 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="text-xl font-bold">
              FlowFront
            </Link>
            <div className="flex space-x-6">
              <Link 
                href="/" 
                className="text-sm font-medium hover:text-gray-600 transition-colors"
              >
                Home
              </Link>
              <Link 
                href="/create-workflow" 
                className="text-sm font-medium hover:text-gray-600 transition-colors"
              >
                Create Workflow
              </Link>
            </div>
          </div>
        </div>
      </nav>

           {children}
        </div>
   
      </body>
    </html>
  );
}
